### ISSUE TITLE
Lista kontaktów przypisanych do poszczególnych grup

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/kontakty#15]
Skoro mamy przypisywanie do grup to trzeba zrobić wyświetlanie kontaktów do nich przypisanych (inaczej ta funkcjonalność nie ma sensu), co oznacza nowy widok, którego w projekcie nie było. Zajmiemy się tym my obaj. Widzę to w ten sposób, że po kliknięciu z listy kontaktów (ekran główny) rekordu wyglądającego jak kontakt (o nazwie Moje grupy) otworzy się widok z listą grup. Na liście, w każdym wierszu znajdować się będzie nazwa grupy oraz suma kontaktów do niej należących. Tutaj trzeba się zastanowić czy próbujemy robić jeden widok na główną listę i wykorzystujemy go też tutaj czy też tworzymy nowy. 

**Termin realizacji: 13.05**

**Comment by bartlomiej-szlachta** [comment]
Spoko pomysł, żeby wchodzić tam z dodatkowego rekordu na górze listy. Ja bym napisał nowy komponent na tą listę, bo wykorzystanie jednego w dwóch miejscach może być niepotrzebnie skomplikowane (w końcu mamy inne komponenty elementów listy, inny header, nie ma FAB itd.). A jak chcesz się podzielić pracą?
