### ISSUE TITLE
Pograć w simsy

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/kontakty#22]
Za ładny ekran szczegółów twoim kolejnym zadaniem będzie pograć sobie cały wieczór w simsy, co najmniej od 18stej. Zadanie proszę udokumentować zrzutami ekranu XD.

**Termin realizacji zadania: 3.05.2020r.**

**Comment by oliwiabrozek** [comment]
![image](https://user-images.githubusercontent.com/34174187/80635198-e06b3200-8a5b-11ea-8f65-acb2195bccc2.png)
