### ISSUE TITLE
Lista funkcjonalności

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/kontakty#4]
1. Dodawanie nowego kontaktu
2. Możliwość dodania więcej niż jednego numeru telefonu
3. Możliwość dodania więcej niż jednego adresu email
4. Możliwość ustawienia zdjęcia z galerii
5. Możliwość ustawienia zdjęcia używając aparatu
6.  Edycja kontaktu
7. Usuwanie co najmniej jednego kontaktu
8. Dodawanie kontaktów do ulubionych
9. Dodawanie kontaktów do grup
10. Przesuwanie w prawo -> zadzwoń
11. Przesuwanie w lewo <- napisz SMS
12. Możliwość wybrania trybu jasnego/ciemnego całej aplikacji

+ dostęp do poszczególnych funkcjonalności z różnych miejsc w aplikacji 

Coś dodać, usunąć? Brak odpowiedzi = zgoda na wszystko, mejla wysyłam jutro, najpóźniej wieczorem.

**Comment by bartlomiej-szlachta** [comment]
7. zaznaczyłbym, że chodzi o **jednoczesne** usuwanie wielu kontaktów

2.5. rozważyłbym dodanie funkcjonalności *ustawianie typu numeru telefonu* (prywatny / służbowy / inny dowolny itp)

- chodzi o to, że będą różne ekrany, więc i różne funkcjonalności na różne ekrany?

**Comment by kamil-blonski** [comment]
w kropce chodzi o to, że np. z wielu miejsc można zadzwonić, wysłać sms czy coś takiego (główna lista, ekran szczegółów)
