### ISSUE TITLE
Błąd edycji kontaktu

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/kontakty#44]
![Screenshot_20200515-181139](https://user-images.githubusercontent.com/37980016/82072383-ee65b780-96d7-11ea-91eb-31b7d406c100.png)

Mój kontakt ma ustawione tylko imię i numer telefonu

**Comment by kamil-blonski** [comment]
Walidacja zdjęć to @kamil-rusin

**Comment by kamil-blonski** [comment]
Albo jednak to ja XD
