### ISSUE TITLE
Błąd dodawania kontaktu do grupy

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/kontakty#45]
![Screenshot_20200515-181614](https://user-images.githubusercontent.com/37980016/82072555-308ef900-96d8-11ea-96c0-f1ce52cea725.png)

Pojawia się, gdy kliknie się zielony pasek na dole formularza dodawania kontaktu, gdy żadne pola nie są uzupełnione

**Comment by kamil-blonski** [comment]
U mnie błąd nie występuje, więcej szczegółów @bartlomiej-szlachta

**Comment by bartlomiej-szlachta** [comment]
Racja, to u mnie się coś z-cache'owało, także nie ma tematu
