### ISSUE TITLE
Poprawa stylizacji na swoich widokach

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/kontakty#53]
Utworzyłem plik ze wspólnymi wartościami dla styli.
@oliwiabrozek  dostosuj swój widok szczegółów,
@kamil-rusin  grupy,
@bartlomiej-szlachta lista,
a ja zmienię w fomularzu.
Pracujcie proszę na gałęzi **common-styles**

Jeśli chodzi o zmiany w kolorach to albo @oliwiabrozek  coś wybierze ładnego albo coś wspólnie ustalimy i wtedy również się to na tej gałęzi zmieni.
Nie ma tu za dużo roboty więc fajnie by było gdybyśmy jutro zamknęli to issue.

**Comment by kamil-rusin** [comment]
Ja byłbym za tym, żeby kwestie kolorów i dostosowania itp w aplikacji zrobiła jedna osoba, która ma 'w głowie' jak aplikacja powinna wyglądać. Jak każdy edytuje swoje to ciężko w 100% jedny styl zrobić.

**Comment by kamil-blonski** [comment]
No to mogę pozmieniać wszędzie tylko niech @oliwiabrozek wybierze jakieś kolorki XD. Nie będzie to jakoś mega dużo więc nie ma problemu

**Comment by oliwiabrozek** [comment]
[Propozycja 1](https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=9E9E9E&secondary.color=FF5722)
[Propozycja 2](https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=2196F3&secondary.color=FFC107)

**Comment by kamil-blonski** [comment]
Mi sie podoba opcja 2, z opcji 1 (może troszkę przyciemnionej) możemy skorzystać do trybu ciemnego, który robi @bartlomiej-szlachta.

**Comment by kamil-rusin** [comment]
Też uważam jak @kamil25963

**Comment by bartlomiej-szlachta** [comment]
Ok
