### ISSUE TITLE
Nie działa FAB

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [Samograje/kontakty#56]
Sprawdziłem i poprawnie nawiguje do ekranu z formularzem, ale ten ekran formularza się wysypuje.

```
undefined is not an object (evaluating 'tempGroupsIds.indexOf')
* src\screens\AddEdit\index.tsx:67:26 in AddEditScreen
```

**Comment by kamil-blonski** [comment]
U mnie błąd nie występuje

**Comment by bartlomiej-szlachta** [comment]
Dobra, to wyczyszczę jeszcze raz dane expo xD

**Comment by bartlomiej-szlachta** [comment]
No i nie ma problemu, działa FAB. Ale dupiato, że to samo z siebie nie ogarnie
