### ISSUE TITLE
Przechowywane dane

### ISSUE THREAD

**Issue by kamil-blonski** [Samograje/kontakty#8]
Powinniśmy dokładnie ustalić jakie dane będziemy przechowywać zanim Kamil zacznie realizować #7 :cat:. Niżej jest przykładowy JSON, jeśli zdecydujemy się coś dodać to zostanie on zaktualizowany, więc obowiązuje ten tutaj na górze. Oczywiście to tylko propozycja, format niekoniecznie poprawny więc proszę się nie czepiać :boom:. Spójrzcie proszę w swoje aplikacje :iphone: kontaktów na telefonach i porównajcie czy jest jeszcze coś co powinniśmy dodać :hatching_chick:. Moja propozycja to `contacts`, czyli wszystkie informacje o danym kontakcie oraz `groups`, czyli grupy globalne, dla wszystkich do wyboru. 

@bartlomiej-szlachta  uwzględniłem twoją propozycję, żeby do numeru przypisać kategorie, chyba o to chodziło.

```
contact:{
	"id": 0
	"firstName": Kamil,
	"secondName": -,
	"surname": Błoński,
	"photo": , 
	"groups": [{group1}, {group2}, {group3}],
	"telNumber":{
		{
			"category": Work,
			"number": 123456789,
		}
		{
			"category": CellPhone,
			"number": 321231321,
		}
		...
	}
	"email":{
		{
			"category": Work,
			"number": 123456789,
		}
		{
			"category": CellPhone,
			"number": 321231321,
		}
		...
	}
}

groups:[{group1}, {group2}, {group3}, ...]
```

**Comment by bartlomiej-szlachta** [comment]
Generalnie spoko 😎 dokładnie o to chodziło z kategoriami numerów 😎  a grupy miałyby tylko nazwę, czy będą obiektami z wieloma parametrami? I jeszcze zastanawia mnie temat przechowywania zdjęć, tu by trzeba było zrobić research. Ale myślę, że tak czy siak klucz `photo` jest spoko, a najwyżej będzie przetrzymywał jakieś ID lub url, jakkolwiek to się robi.

**Comment by kamil-blonski** [comment]
A co byś chciał przechowywać dodatkowo w grupach?
